export const singleOrderItem = {
  sn: 1,
  xid: 'aXrLJbp7',
  item_id: 'Q1WR5vbm',
  name: 'Samsung Galaxy M32 5G',
  image: '71os5DRhuSL._AC_UY218_.jpg',
  image_url:
    'https://demo.stockifly.in/uploads/products/71os5DRhuSL._AC_UY218_.jpg',
  x_tax_id: '',
  discount_rate: 0,
  total_discount: 0,
  total_tax: 0,
  unit_price: 32.25,
  single_unit_price: 32.25,
  subtotal: 2580,
  quantity: 80,
  tax_rate: 0,
  tax_type: 'exclusive',
  x_unit_id: 'AdWNDqgV',
  unit: {
    company_id: 1,
    name: 'piece',
    short_name: 'pc',
    base_unit: null,
    operator: 'multiply',
    operator_value: '1',
    is_deletable: 0,
    created_at: null,
    updated_at: null,
    xid: 'AdWNDqgV',
  },
  stock_quantity: 80,
  unit_short_name: 'pc',
};

export const orderItemsData = [singleOrderItem];

export const singleOrder = {
  unique_id: 'tG0zl9ZY1H3pMZeFt9rN',
  invoice_number: '5434654654',
  order_type: 'sales',
  order_date: '2024-01-31T06:19:52+00:00',
  tax_amount: 258,
  discount: 0,
  shipping: 0,
  subtotal: 2580,
  paid_amount: 2838,
  due_amount: 0,
  order_status: 'processing',
  payment_status: 'paid',
  total: 2838,
  tax_rate: 10,
  cancelled: 0,
  terms_condition:
    '1. Goods once sold will not be taken back or exchanged\n\t2. All disputes are subject to [ENTER_YOUR_CITY_NAME] jurisdiction only',
  xid: '8Vbnderk',
  x_warehouse_id: 'AdWNDqgV',
  x_from_warehouse_id: null,
  x_staff_user_id: 'AdWNDqgV',
  x_user_id: '3BrZZXrA',
  warehouse: {
    name: 'Electronifly',
    xid: 'AdWNDqgV',
  },
  from_warehouse: null,
  staff_member: {
    name: 'Admin',
    profile_image: null,
    user_type: 'staff_members',
    xid: 'AdWNDqgV',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  user: {
    user_type: 'customers',
    name: 'Arielle Franecki',
    profile_image: null,
    phone: '+16024298929',
    xid: '3BrZZXrA',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  order_payments: [
    {
      amount: 2838,
      xid: 'mKbKobL7',
      x_payment_id: 'mKbKobL7',
      payment: {
        amount: 2838,
        date: '2024-01-31T00:00:00+00:00',
        notes: null,
        xid: 'mKbKobL7',
        x_payment_mode_id: '7ZWDkbpO',
        payment_mode: {
          name: 'Paypal',
          xid: '7ZWDkbpO',
        },
      },
    },
  ],
  items: [
    {
      single_unit_price: 32.25,
      unit_price: 32.25,
      quantity: 80,
      tax_rate: 0,
      total_tax: 0,
      tax_type: 'exclusive',
      total_discount: 0,
      subtotal: 2580,
      xid: 'Q1WR5vbm',
      x_product_id: 'aXrLJbp7',
      product: {
        name: 'Samsung Galaxy M32 5G',
        image: '71os5DRhuSL._AC_UY218_.jpg',
        xid: 'aXrLJbp7',
        x_unit_id: 'AdWNDqgV',
        image_url:
          'https://demo.stockifly.in/uploads/products/71os5DRhuSL._AC_UY218_.jpg',
        unit: {
          name: 'piece',
          short_name: 'pc',
          xid: 'AdWNDqgV',
        },
        details: {
          current_stock: 0,
          xid: 'aXrLJbp7',
          x_warehouse_id: 'AdWNDqgV',
          x_product_id: 'aXrLJbp7',
          x_tax_id: null,
        },
      },
      order_item_taxes: [],
    },
  ],
  shipping_address: null,
};

export const ordersData = [singleOrder];
